import type {GearInfo} from "../types"

export const GEAR: GearInfo[] = [
    {
        name: "Arrows",
        cost: {gp: 0, sp: 0, cp: 5},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 20, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Backpack",
        cost: {gp: 2, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 1},
    },
    {
        name: "Ball bearing",
        cost: {gp: 1, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 0, freeCarry: 0},
    },
    {
        name: "Bolas",
        cost: {gp: 2, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 0, freeCarry: 0},
    },
    {
        name: "Bottle",
        cost: {gp: 0, sp: 3, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Bucket",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 0, freeCarry: 1},
    },
    {
        name: "Caltrops",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Candle",
        cost: {gp: 0, sp: 0, cp: 2},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 3, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Charcoal jar",
        cost: {gp: 1, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Crossbow Bolts",
        cost: {gp: 0, sp: 0, cp: 5},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 20, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Crowbar",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Flash seed",
        cost: {gp: 1, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Flask",
        cost: {gp: 0, sp: 3, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Flint and Steel",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Glow paste jar",
        cost: {gp: 2, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Grappling Hook",
        cost: {gp: 1, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Holy water flask",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Iron Spikes",
        cost: {gp: 0, sp: 1, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 10, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Health Potion",
        desc: "Heal 1d6 hp",
        cost: {gp: 0, sp: 1, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Lantern",
        cost: {gp: 5, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Lantern hook",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Miner's putty jar",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Mirror",
        cost: {gp: 10, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Net",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Oil flask",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Pole",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Rations",
        cost: {gp: 0, sp: 2, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 3, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Rope, 60'",
        cost: {gp: 1, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Rope, morzo silk",
        cost: {gp: 50, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Saddle",
        cost: {gp: 30, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Spear-thrower",
        cost: {gp: 2, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 3, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Tallow jar",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Torch",
        cost: {gp: 0, sp: 5, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Traveler's lamp",
        cost: {gp: 10, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Wagon",
        cost: {gp: 120, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 0},
    },
    // #################################################################################################################
    // --------------------------------------------Spell Scrolls/Wands--------------------------------------------------
    // #################################################################################################################
    {
        name: "Light Spell",
        cost: {gp: 0, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 1},
    },
    {
        name: "Light Spell (Double Range)",
        cost: {gp: 0, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 1},
    },
    {
        name: "Light Spell (Double Time)",
        cost: {gp: 0, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 1, freeCarry: 1},
    },
    // #################################################################################################################
    // ----------------------------------------------Class Items--------------------------------------------------------
    // #################################################################################################################
    {
        name: "Kyzian Arrow",
        cost: {gp: 0, sp: 0, cp: 5},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 80, slotsUsed: 1, freeCarry: 0},
    },
    {
        name: "Holy Symbol",
        cost: {gp: 0, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 0, freeCarry: 1},
    },
    {
        name: "Thieving Tools",
        cost: {gp: 0, sp: 0, cp: 0},
        canBeEquipped: false,
        type: "Basic",
        slots: {perSlot: 1, slotsUsed: 0, freeCarry: 1},
    },
]

const GEAR_COMPENDIUM: { [name: string]: GearInfo } = {}
for (const g of GEAR) {
    GEAR_COMPENDIUM[g.name.toLowerCase()] = g
}

export default GEAR_COMPENDIUM
