import type {SpellInfo} from "../types";

export const SPELLS: SpellInfo[] = [
    // #################################################################################################################
    // ----------------------------------------------Tier 1 Spells------------------------------------------------------
    // #################################################################################################################
    {
        name: "Alarm",
        range: "Close",
        class: "Wizard",
        tier: 1,
        desc: "You touch one object, such as a door threshold, setting a magical alarm on it. If any creature you do not designate while casting the spell touches or crosses past the object, a magical bell sounds in your head.",
        duration: {type: "Day", amt: 1},
    },
    {
        name: "Burning Hands",
        range: "Close",
        class: "Wizard",
        tier: 1,
        damage: {diceType: "d6", numDice: 1},
        desc: "You spread your fingers with thumbs touching, unleashing a circle of flame that fills a close area around where you stand. Creatures within the area of effect take 1d6 damage. Unattended flammable objects ignite.",
        duration: {type: "Instant"},
    },
    {
        name: "Cauldron",
        range: "Close",
        class: "Witch",
        tier: 1,
        desc: " You conjure a bubbling cauldron next to you. It can produce one of the following effects: \n" +
            "• Any broken mundane item placed inside the cauldron is repaired. \n" +
            "• A fat, croaking toad leaps out and follows your instructions for the next 3 rounds. \n" +
            "• You can place up to 3 item slots of items inside the cauldron. The cauldron expels these items the next time you cast this spell (expelling items counts as the cauldron's single effect)",
        duration: {type: "Round", amt: 1},
    },
    {
        name: "Chant",
        range: "Self",
        class: "Seer",
        tier: 1,
        desc: "You begin an unearthly chant that lifts your vision beyond its ordinary limitations. For the spell's duration, you can see all invisible and hidden things as though they were plainly visible. This spell does not allow you to see in a way that you could not normally, such as in darkness or through walls.",
        duration: {type: "Focus"},
    },
    {
        name: "Charm Person",
        range: "Near",
        class: "Wizard, Witch",
        tier: 1,
        desc: "You magically beguile one humanoid of LV 2 or less within near range, who regards you as a friend for the duration. The spell ends if you or your allies do anything harmful to the target. The target knows it was magically charmed after the spell ends. Roll 1d8 to determine amount of days effective",
        duration: {type: "Day", roll: {numDice: 1, diceType: "d8"}},
    },
    {
        name: "Cure Wounds",
        range: "Close",
        class: "Priest",
        tier: 1,
        desc: "Your touch restores ebbing life. Roll a number of d6s equal to 1 + half your level (rounded down). One target you touch regains that much HP.", // TODO
        duration: {type: "Instant"},
    },
    {
        name: "Detect Magic",
        range: "Near",
        class: "Wizard",
        tier: 1,
        desc: "You can sense the presence of magic within near range for the spell's duration. If you focus for two rounds, you discern its general properties. Full barriers block this spell.",
        duration: {type: "Focus"},
    },
    {
        name: "Evoke Rage",
        range: "Close",
        class: "Seer",
        tier: 1,
        damage: {diceType: "d4", numDice: 1},
        desc: "You call out the berserk rage locked inside someone. One willing humanoid you touch enters a berserk state. The target is immune to morale checks, has ADV on STR checks and melee attacks, and deals +1d4 damage for the spell's duration. If the target does not attack another creature on its turn, the spell ends.",
        duration: {type: "Round", roll: {numDice: 1, diceType: "d4"}},
    },
    {
        name: "Eyebite",
        range: "Near",
        class: "Witch",
        tier: 1,
        damage: {diceType: "d4", numDice: 1},
        desc: "One creature you target takes 1d4 damage, and it can't see you until the end of its next turn.",
        duration: {type: "Instant"},
    },
    {
        name: "Feather Fall",
        range: "Self",
        class: "Wizard",
        tier: 1,
        desc: "You may make an attempt to cast this spell when you fall. Your rate of descent slows so that you land safely on your feet.",
        duration: {type: "Instant"},
    },
    {
        name: "Floating Disk",
        range: "Near",
        class: "Wizard",
        tier: 1,
        desc: "You create a floating, circular disk of force with a concave center. It can carry up to 20 gear slots. It hovers at waist level and automatically stays within near of you. It can’t cross over drop- offs or pits taller than a human.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Fog",
        range: "Close",
        class: "Witch",
        tier: 1,
        desc: "A thick cloud of fog blooms in a close area around you, making you hard to see. The cloud moves with you. Attacks against creatures in the cloud have disadvantage.",
        duration: {type: "Focus"},
    },
    {
        name: "Hold Portal",
        range: "Near",
        class: "Wizard",
        tier: 1,
        desc: "You magically hold a portal closed for the duration. A creature must make a successful STR check vs. your spellcasting check to open the portal. The knock spell ends this spell.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Holy Weapon",
        range: "Close",
        class: "Priest",
        tier: 1,
        desc: "One weapon you touch is imbued with a sacred blessing. The weapon becomes magical and has +1 to attack and damage rolls for the duration.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Hypnotize",
        range: "Near",
        class: "Witch",
        tier: 1,
        desc: "One creature of LV 3 or less that can see you is rendered stupefied. Breaking the creature's line of sight to you allows it to make a DC 15 Charisma check. On a success, the spell ends.",
        duration: {type: "Focus"},
    },
    {
        name: "Light",
        range: "Close",
        class: "Priest, Wizard",
        tier: 1,
        desc: "One object you touch glows with bright, heatless light, illuminating out to a near distance for 1 hour of real time.",
        duration: {type: "Hour", subType: "RealTime", amt: 1},
    },
    {
        name: "Mage Armor",
        range: "Self",
        class: "Wizard",
        tier: 1,
        desc: "An invisible layer of magical force protects your vitals. Your armor class becomes 14 (18 on a critical spellcasting check) for the spell’s duration.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Magic Missile",
        range: "Far",
        class: "Wizard",
        tier: 1,
        damage: {diceType: "d4", numDice: 1},
        desc: "You have advantage on your check to cast this spell. A glowing bolt of force streaks from your open hand, dealing 1d4 damage to one target.",
        duration: {type: "Instant"},
    },
    {
        name: "Oak, Ash, Thorn",
        range: "Self",
        class: "Witch",
        tier: 1,
        desc: "For the spell's duration, faeries, demons, and devils can't attack you. These beings also can't possess, compel, or beguile you.",
        duration: {type: "Focus"},
    },
    {
        name: "Potion",
        range: "Close",
        class: "Seer",
        tier: 1,
        desc: "As a part of casting this spell, you must bless a single drink of any liquid. The liquid gains healing properties for 1 day. A creature who imbibes it may end the effects of one poison or may immediately stop dying (the creature remains at 0 HP).",
        duration: {type: "Instant"},
    },
    {
        name: "Puppet",
        range: "Close",
        class: "Witch",
        tier: 1,
        desc: "One humanoid creature of LV 2 or less you touch becomes ensnared by your movements. On your turn, the creature mimics all your movements. If mimicking you would cause the creature to directly harm itself or an ally, it can make a DC 15 Charisma check. On a success, it resists mimicking you.",
        duration: {type: "Focus"},
    },
    {
        name: "Protection From Evil",
        range: "Close",
        class: "Priest, Wizard",
        tier: 1,
        desc: "For the spell’s duration, chaotic beings have disadvantage on attack rolls and hostile spellcasting checks against the target. These beings also can’t possess, compel, or beguile it. When cast on an already-possessed target, the possessing entity makes a CHA check vs. the last spellcasting check. On a failure, the entity is expelled.",
        duration: {type: "Focus"},
    },
    {
        name: "Shadowdance",
        range: "Near",
        class: "Witch",
        tier: 1,
        desc: "You spin shadowstuff into a convincing visible and audible illusion at a point within near. The illusion can be as big as a person and can move within a near range of where it appeared. The illusion can't affect physical objects. Touching the illusion reveals its false nature.",
        duration: {type: "Round", amt: 3},
    },
    {
        name: "Shield of Faith",
        range: "Self",
        class: "Priest",
        tier: 1,
        desc: "A protective force wrought of your holy conviction surrounds you. You gain a +2 bonus to your armor class for the duration.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Sleep",
        range: "Near",
        class: "Wizard",
        tier: 1,
        desc: "This spell fills a near-sized cube extending from you. Choose a number of living creatures in the area up to your level. Those creatures fall into a deep sleep if they are LV 2 or less. Injury or vigorous shaking wakes them.",
        duration: {type: "Instant"},
    },
    {
        name: "Trance",
        range: "Close",
        class: "Seer",
        tier: 1,
        desc: "You enter a trance, catching small glimpses of a creature's fate. One humanoid creature you touch (you can't target yourself) gains a luck token. It can't have more than one luck token at once.",
        duration: {type: "Instant"},
    },
    {
        name: "Willowman",
        range: "Near",
        class: "Witch",
        tier: 1,
        desc: "You call upon the Willowman to appear in one creature's mind, filling it with supernatural terror. Choose one creature of LV 2 or less within range. That creature must immediately make a morale check. Even creatures that are not normally subject to morale checks (such as undead) must do so.",
        duration: {type: "Instant"},
    },
    {
        name: "Witchlight",
        range: "Near",
        class: "Witch",
        tier: 1,
        desc: "You summon a floating marsh light that bobs in the air and casts light out to a close radius around it. The light can change colors and take on vague shapes. It can float up to a near distance on your turn.",
        duration: {type: "Focus"},
    },
    // #################################################################################################################
    // ----------------------------------------------Tier 2 Spells------------------------------------------------------
    // #################################################################################################################
    {
        name: "Acid Arrow",
        range: "Far",
        class: "Wizard",
        tier: 2,
        damage: {diceType: "d6", numDice: 1},
        desc: "You conjure a corrosive bolt that hits one foe, dealing 1d6 damage a round. The bolt remains in the target for as long as you focus.",
        duration: {type: "Focus"},
    },
    {
        name: "Alter Self",
        range: "Self",
        class: "Wizard, Witch",
        tier: 2,
        desc: "You magically change your physical form, gaining one feature that modifies your existing anatomy. For example, you can grow functional gills on your neck or bear claws on your fingers. This spell can’t grow wings or limbs.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Augury",
        range: "Self",
        class: "Priest, Witch",
        tier: 2,
        desc: "You interpret the meaning of supernatural portents and omens. Ask the GM one question about a specific course of action. The GM says whether the action will lead to “weal” or “woe.”",
        duration: {type: "Instant"},
    },
    {
        name: "Bless",
        range: "Close",
        class: "Priest",
        tier: 2,
        desc: "One creature you touch gains a luck token.",
        duration: {type: "Instant"},
    },
    {
        name: "Blind/Deafen",
        range: "Near",
        class: "Priest",
        tier: 2,
        desc: "You utter a divine censure, blinding or deafening one creature you can see in range. The creature has disadvantage on tasks requiring the lost sense.",
        duration: {type: "Focus"},
    },
    {
        name: "Bogboil",
        range: "Far",
        class: "Witch",
        tier: 2,
        desc: "You turn a near-sized cube of ground within range into a muddy, boiling bog of quicksand. A creature stuck in the bog can't move and must succeed on a Dexterity check vs. your spellcasting check to free itself.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Cacklerot",
        range: "Close",
        class: "Witch",
        tier: 2,
        desc: "One target you touch of LV 4 or less collapses helplessly with disturbing, pained laughter for the spell's duration.",
        duration: {type: "Focus"},
    },
    {
        name: "Cat's Eye",
        range: "Self",
        class: "Witch",
        tier: 2,
        desc: "Your irises grow to fill your eyes and your pupils turn into black, vertical slits. You can see invisible creatures and secret doors for the spell's duration.",
        duration: {type: "Focus"},
    },
    {
        name: "Cleansing Weapon",
        range: "Close",
        class: "Priest",
        tier: 2,
        desc: "One weapon you touch is wreathed in purifying flames. It deals an additional 1d4 damage (1d6 vs. undead) for the duration.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Detect Thoughts",
        range: "Near",
        class: "Wizard",
        tier: 2,
        desc: "You peer into the mind of one creature you can see within the spell’s range. Each round, you learn the target’s immediate thoughts. On its turn, the target makes a Wisdom check opposed by your last spellcasting check. If the target succeeds, it notices your presence in its mind and the spell ends.",
        duration: {type: "Focus"},
    },
    {
        name: "Fate",
        range: "Near",
        class: "Seer",
        tier: 2,
        damage: {diceType: "d10", numDice: 1},
        desc: "You painfully twist the golden threads of a creature's fate. One creature you target in range takes 1d10 damage and loses any luck tokens it has.",
        duration: {type: "Instant"},
    },
    {
        name: "Fixed Object",
        range: "Close",
        class: "Wizard",
        tier: 2,
        desc: "An object you touch that weighs no more than 5 pounds becomes fixed in its current location. It can support up to 5,000 pounds of weight for the duration of the spell.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Frog Rain",
        range: "Far",
        class: "Witch",
        tier: 2,
        damage: {diceType: "d6", numDice: 1},
        desc: "A rain of indignant frogs pelts a near-sized cube around a point you can see within range. All creatures within the frog rain take 1d6 damage. Any surviving frogs hop away and disappear.",
        duration: {type: "Instant"},
    },
    {
        name: "Hold Person",
        range: "Near",
        class: "Wizard",
        tier: 2,
        desc: "You magically paralyze one humanoid creature of LV 4 or less you can see within range.",
        duration: {type: "Focus"},
    },
    {
        name: "Invisibility",
        range: "Close",
        class: "Wizard, Witch",
        tier: 2,
        desc: "A creature you touch becomes invisible for the spell’s duration. The spell ends if the target attacks or casts a spell.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Knock",
        range: "Near",
        class: "Wizard",
        tier: 2,
        desc: "A door, window, gate, chest, or portal you can see within range instantly opens, defeating all mundane locks and barriers. This spell creates a loud knock audible to all within earshot.",
        duration: {type: "Instant"},
    },
    {
        name: "Levitate",
        range: "Self",
        class: "Wizard",
        tier: 2,
        desc: "You can float a near distance vertically per round on your turn. You can also push against solid objects to move horizontally.",
        duration: {type: "Focus"},
    },
    {
        name: "Mirror Image",
        range: "Self",
        class: "Wizard",
        tier: 2,
        desc: "You create a number of illusory duplicates of yourself equal to half your level rounded down (minimum 1). The duplicates surround you and mimic you. Each time a creature attacks you, the attack misses and causes one of the duplicates to evaporate. If all of the illusions have disappeared, the spell ends.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Misty Step",
        range: "Self",
        class: "Wizard",
        tier: 2,
        desc: "In a puff of smoke, you teleport a near distance to an area you can see.",
        duration: {type: "Instant"},
    },
    {
        name: "Poison",
        range: "Close",
        class: "Witch",
        tier: 2,
        desc: "One worn or carried object you touch becomes toxic for the spell's duration. Any creature in contact with the object at the start of its turn takes 1d6 damage.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Read The Runes",
        range: "Self",
        class: "Seer",
        tier: 2,
        desc: "You ask the gods a question and cast the runestones, interpreting the meaning of the results. Ask the Game Master one yes or no question. The Game Master truthfully answers 'yes' or 'no.'",
        duration: {type: "Instant"},
    },
    {
        name: "Sacrifice",
        range: "Close",
        class: "Seer",
        tier: 2,
        desc: "As a part of casting this spell, you must ritually sacrifice a living creature of LV 2 or higher. The target you touch gains a bonus to their next check or attack roll equal to the sacrificed creature's level.",
        duration: {type: "Instant"},
    },
    {
        name: "Silence",
        range: "Far",
        class: "Wizard",
        tier: 2,
        desc: "You magically mute sound in a near cube within the spell’s range. Creatures inside the area are deafened, and any sounds they create cannot be heard.",
        duration: {type: "Focus"},
    },
    {
        name: "Smite",
        range: "Near",
        class: "Priest",
        tier: 2,
        damage: {diceType: "d6", numDice: 1},
        desc: "You call down punishing flames on a creature you can see within range. It takes 1d6 damage.",
        duration: {type: "Instant"},
    },
    {
        name: "Soulbind",
        range: "Close",
        class: "Seer",
        tier: 2,
        desc: "You seal the soul of a living creature, preventing magic from leeching into it. One creature you touch becomes nearly impervious to all magic. For the spell's duration, all other spells targeting the creature (harmful or helpful) are DC 18 to cast. This spell ends as soon as the target is affected by another spell.",
        duration: {type: "Focus"},
    },
    {
        name: "Spidersilk",
        range: "Self",
        class: "Witch",
        tier: 2,
        desc: "Sticky spidersilk covers your hands and feet. For the spell's duration, you can walk on vertical surfaces as easily as if it were flat ground.",
        duration: {type: "Focus"},
    },
    {
        name: "Toadstool",
        range: "Self",
        class: "Witch",
        tier: 2,
        heal: {diceType: "d6", numDice: 1},
        desc: "You conjure a plump, speckled toadstool in your hand. It disappears at the end of your next turn. A creature that eats the toadstool regains 1d6 HP.",
        duration: {type: "Instant"},
    },
    {
        name: "Web",
        range: "Far",
        class: "Wizard",
        tier: 2,
        desc: "You create a near-sized cube of sticky, dense spider web within the spell’s range. A creature stuck in the web can’t move and must succeed on a Strength check opposed by your spellcasting check to free itself.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Zone of Truth",
        range: "Near",
        class: "Priest",
        tier: 2,
        desc: "You compel a creature you can see to speak truth. It can’t utter a deliberate lie while within range.",
        duration: {type: "Focus"},
    },
    // #################################################################################################################
    // ----------------------------------------------Tier 3 Spells------------------------------------------------------
    // #################################################################################################################
    {
        name: "Animate Dead",
        range: "Close",
        class: "Wizard",
        tier: 3,
        desc: "You touch one humanoid’s remains, and it rises as a zombie or skeleton under your control. The remains must have at least three limbs and its head intact. The undead creature acts on your turn. After 1 day, the creature collapses into grave dust.",
        duration: {type: "Day", amt: 1},
    },
    {
        name: "Broomstick",
        range: "Self",
        class: "Witch",
        tier: 3,
        desc: "You conjure a flying broomstick in your hand. The broomstick's rider can fly a near distance each round and can hover in place.",
        duration: {type: "Focus"},
    },
    {
        name: "Cast Out",
        range: "Far",
        class: "Seer",
        tier: 3,
        desc: "You turn a creature aside, throwing it out of your presence. Choose a creature you can see. For the spell's duration, that creature can't come within near range of you. It can still attack you from outside of near range.",
        duration: {type: "Focus"},
    },
    {
        name: "Command",
        range: "Far",
        class: "Priest",
        tier: 3,
        duration: {type: "Focus"},
        desc: "You issue a verbal command to one creature in range who can understand you. The command must be one word, such as “kneel.” The target obeys the command for as long as you focus. If your command is ever directly harmful to the creature, it may make a Charisma check vs. your last spellcasting check. On a success, the spell ends.",
    },
    {
        name: "Coven",
        range: "Self",
        class: "Witch",
        tier: 3,
        desc: "You call upon the magic you share with your fellow witches. You regain the use of one tier 3 spell or lower that you can no longer cast for the day. After successfully casting this spell, you can't do so again until you complete a rest.",
        duration: {type: "Instant"},
    },
    {
        name: "Dispel Magic",
        range: "Near",
        class: "Wizard",
        tier: 3,
        duration: {type: "Instant"},
        desc: "End one spell that affects one target you can see in range.",
    },
    {
        name: "Divination",
        range: "Self",
        class: "Witch",
        tier: 3,
        desc: "You throw the divining bones or peer into the blackness between the stars, seeking a portent. You can ask the GM one yes or no question. The GM truthfully answers 'yes' or 'no'. If you cast this spell more than once in 24 hours, treat a failed spellcasting check for it as a critical failure instead.",
        duration: {type: "Instant"},
    },
    {
        name: "Fabricate",
        range: "Near",
        class: "Wizard",
        tier: 3,
        desc: "This spell can't target creatures. You turn a tree-sized collection of raw materials into a finished work. For example, you convert a pile of bricks or rocks into a bridge. The finished work converts back to raw materials when the spell ends.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Fireball",
        range: "Far",
        class: "Wizard",
        tier: 3,
        damage: {diceType: "d6", numDice: 4},
        desc: "You hurl a small flame that erupts into a fiery blast. All creatures in a near-sized cube around where the flame lands take 4d6 damage.",
        duration: {type: "Instant"},
    },
    {
        name: "Fly",
        range: "Self",
        class: "Wizard",
        tier: 3,
        desc: "Your feet lift from the ground, and you take to the air like a hummingbird. You can fly near for the spell's duration and are able to hover in place.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Gaseous Form",
        range: "Self",
        tier: 3,
        class: "Wizard",
        desc: "You and your gear turn into a cloud of smoke for the spell's duration. You can fly and pass through any gap that smoke could. You can sense the terrain and any movement around you out to a near distance. You can't cast spells while in this form.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Hallucinate",
        range: "Near",
        class: "Seer",
        tier: 3,
        desc: "One creature you target in near whose level is less than or equal to your own is overcome by visions of what might yet come to pass. For the spell's duration, the target cannot act on its turn unless it passes a Wisdom check equal to your last spellcasting check.",
        duration: {type: "Focus"},
    },
    {
        name: "Howl",
        range: "Near",
        class: "Witch",
        tier: 3,
        desc: "All enemies within near range of you must immediately make a morale check. This spell does not affect creatures that are immune to morale checks.",
        duration: {type: "Instant"},
    },
    {
        name: "Illusion",
        tier: 3,
        class: "Wizard",
        range: "Far",
        desc: "You create a convincing visible and audible illusion that fills up to a near-sized cube in range. The illusion cannot cause harm, but creatures who believe the illusion is real react to it as though it were. A creature who inspects the illusion from afar must pass a Wisdom check vs. your last spellcasting check to perceive the false nature of the illusion. Touching the illusion also reveals its false nature.",
        duration: {type: "Focus"},
    },
    {
        name: "Lay To Rest",
        tier: 3,
        class: "Priest",
        range: "Close",
        desc: "You instantly send an undead creature you touch to its final afterlife, destroying it utterly. You can target an undead creature of LV 9 or less.",
        duration: {type: "Instant"},
    },
    {
        name: "Lighting Bolt",
        tier: 3,
        class: "Wizard",
        range: "Far",
        damage: {diceType: "d6", numDice: 3},
        desc: "You shoot a blue-white ray of lightning from your hands, hitting all creatures in a straight line out to a far distance. Creatures struck by the lightning take 3d6 damage.",
        duration: {type: "Instant"},
    },
    {
        name: "Magic Circle",
        tier: 3,
        class: "Wizard",
        range: "Near",
        desc: "You conjure a circle of runes out to near-sized cube centered on yourself and name a type of creature (for example, demons). For the spell’s duration, creatures of the chosen type cannot attack or cast a hostile spell on anyone inside the circle. The chosen creatures also can’t possess, compel, or beguile anyone inside the circle.",
        duration: {type: "Focus"},
    },
    {
        name: "Mass Cure",
        tier: 3,
        class: "Priest",
        range: "Near",
        heal: {diceType: "d6", numDice: 2},
        desc: "All allies within near range of you regain 2d6 HP.",
        duration: {type: "Instant"},
    },
    {
        name: "Mistletoe",
        range: "Near",
        class: "Witch",
        tier: 3,
        desc: "Two creatures you can see within near of you become enchanted with each other for 1d8 days. Each time one of the affected creatures takes damage, it may make a DC 15 Charisma check. On a success, the spell ends.",
        duration: {type: "Day", roll: {numDice: 1, diceType: "d8"}},
    },
    {
        name: "Pin Doll",
        range: "Plane",
        class: "Witch",
        tier: 3,
        damage: {diceType: "d6", numDice: 2},
        desc: "You pin a piece of hair or flesh taken from one creature to a small, burlap doll the spell conjures. On your turn while focusing on this spell, you can push a pin into the doll. Each time you do this, the creature who the hair or flesh belonged to takes 2d6 damage. After this spell ends, the piece of hair or flesh burns to ash.",
        duration: {type: "Focus"},
    },
    {
        name: "Protection From Energy",
        tier: 3,
        class: "Wizard",
        range: "Close",
        desc: "One creature you touch becomes impervious to the wild fury of the elements. Choose fire, cold, or electricity. For the spell's duration, the target is immune to harm from energy of the chosen type.",
        duration: {type: "Focus"},
    },
    {
        name: "Raven",
        range: "Unlimited",
        class: "Seer",
        tier: 3,
        desc: "You whisper a message to Odin's own ravens, and they carry it across all worlds to its recipient. Speak a short sentence, and the name of its recipient, dead or alive. That creature hears your utterance whispered in its mind.",
        duration: {type: "Instant"},
    },
    {
        name: "Rebuke Unholy",
        tier: 3,
        class: "Priest",
        range: "Near",
        desc: "You rebuke creatures who oppose your alignment, forcing them to flee. You must present a holy symbol to cast this spell. If you are lawful or neutral, this spell affects demons, devils, and outsiders. If you are chaotic, this spell affects angels and natural creatures of the wild. Affected creatures within near of you must make a CHA check vs. your spellcasting check. If a creature fails by 10+ points and is equal to or less than your level, it is destroyed. Otherwise, on a fail, it flees from you for 5 rounds.",
        duration: {type: "Instant"},
    },
    {
        name: "Restoration",
        tier: 3,
        class: "Priest",
        range: "Close",
        desc: "With the touch of your hands, you expunge curses and illnesses. One curse, illness, or affliction of your choice affecting the target creature ends.",
        duration: {type: "Instant"},
    },
    {
        name: "Sending",
        tier: 3,
        class: "Wizard",
        range: "Far",
        desc: "Range Unlimited. You send a brief, mental message to any creature with whom you are familiar who is on the same plane.",
        duration: {type: "Instant"},
    },
    {
        name: "Speak With Dead",
        tier: 3,
        class: "Wizard, Witch",
        range: "Close",
        desc: 'A dead body you touch answers your questions in a distant, wheezing voice. You can ask the dead body up to three yes or no questions (one at a time). The GM truthfully answers "yes" or "no" to each. If you cast this spell more than once in 24 hours, treat a failed spellcasting check for it as a critical failure, instead.',
        duration: {type: "Instant"},
    },
    {
        name: "Swarm",
        range: "Far",
        class: "Witch",
        tier: 3,
        desc: "A dense swarm of biting bats, rats, or locusts appears in a nearsized cube around a point you can see within range. All creatures that start their turn within the swarm take 2d6 damage and are blinded.",
        duration: {type: "Focus"},
    },
    {
        name: "Void Stare",
        range: "Far",
        class: "Witch",
        tier: 3,
        desc: "Your eyes turn black as you look into the dark between the stars. One creature of LV 6 or less you can see falls under your control. You decide its actions during its turn.",
        duration: {type: "Focus"},
    },
    {
        name: "Whisper",
        range: "Close",
        class: "Witch",
        tier: 3,
        desc: "You whisper into another creature's ear, planting a false memory in its mind. You describe one brief, false memory that the target believes is true going forward. If you fail this spellcasting check, the GM chooses a short, false memory to plant in your mind instead.",
        duration: {type: "Instant"},
    },
    {
        name: "Wolfshape",
        range: "Self",
        class: "Seer",
        tier: 3,
        desc: "You and your gear transform into a wolf for the spell's duration. You assume the wolf's STR, DEX, CON, HP, AC, speed, attacks, and physical characteristics, but retain your INT, WIS, and CHA. You can cast spells in this form. If you go to 0 HP, you revert to your true shape at 0 HP. If you are level 5+, you can transform into a dire wolf or a winter wolf instead.",
        duration: {type: "Focus"},
    },
    // #################################################################################################################
    // ----------------------------------------------Tier 4 Spells------------------------------------------------------
    // #################################################################################################################
    {
        name: "Arcane Eye",
        range: "Near",
        class: "Wizard",
        tier: 4,
        desc: "You conjure an invisible, grape- sized eye within range. You can see through the eye. It can see in the dark out to near range, fly near on your turn, and squeeze through openings as narrow as a keyhole.",
        duration: {type: "Focus"},
    },
    {
        name: "Beguile",
        range: "Near",
        class: "Witch",
        tier: 4,
        desc: "You conjure a convincing visible and audible illusion within range. Creatures who perceive the illusion react to it as though it were real, although it can't cause actual harm. Touching the illusion instantly reveals its false nature. You may force a creature who interacts with the illusion to make a DC 15 Wisdom check. If the creature fails, it is enchanted by the illusion for the spell's duration and seeks to protect it.",
        duration: {type: "Focus"},
    },
    {
        name: "Cloak of Night",
        range: "Self",
        class: "Witch",
        tier: 4,
        desc: "Your wrap yourself in a swirling cloak of shadows. For the spell's duration, your armor class becomes 17 (20 on a critical spellcasting check). You have advantage on Dexterity checks to sneak and hide for the spell's duration.",
        duration: {type: "Round", amt: 8},
    },
    {
        name: "Cloudkill",
        range: "Far",
        class: "Wizard",
        tier: 4,
        desc: "A putrid cloud of yellow poison fills a near-sized cube within range. It spreads around corners. Creatures inside the cloud are blinded and take 2d6 damage at the beginning of their turns. A creature of LV 9 or less that ends its turn fully inside the cloud dies.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Commune",
        range: "Self",
        class: "Priest",
        tier: 4,
        desc: 'You seek your god\'s counsel. Ask the GM up to three yes or no questions. The GM truthfully answers "yes" or "no" to each. If you cast this spell more than once in 24 hours, treat a failed spellcasting check for it as a critical failure, instead.',
        duration: {type: "Instant"},
    },
    {
        name: "Confusion",
        range: "Near",
        class: "Wizard",
        tier: 4,
        desc: "You mesmerize one creature you can see in range. The target can't take actions, and it moves in a random direction on its turn. If the target is LV 9+, it may make a WIS check vs. your last spellcasting check at the start of its turn to end the spell.",
        duration: {type: "Focus"},
    },
    {
        name: "Control Water",
        range: "Far",
        class: "Wizard",
        tier: 4,
        desc: "You move and shape water. You can cause a section of water up to 100 feet in width and depth to change shape, defy gravity, or flow in a different direction.",
        duration: {type: "Focus"},
    },
    {
        name: "Curse",
        range: "Close",
        class: "Witch",
        tier: 4,
        desc: "A creature you touch is afflicted by one of the following curses: \n" +
            "• Hideous boils and warts \n" +
            "• All food tastes of ash \n" +
            "• Voice becomes shrill \n" +
            "• Disturbing nightmares \n" +
            "• Always lose at gambling \n" +
            "• An ally turns into an enemy \n" +
            "• Fear of something ordinary",
        duration: {type: "Permanent", amt: 8},
    },
    {
        name: "Dimension Door",
        range: "Self",
        class: "Wizard, Witch",
        tier: 4,
        desc: "You teleport yourself and up to one other willing creature to any point you can see.",
        duration: {type: "Instant"},
    },
    {
        name: "Divination",
        range: "Self",
        class: "Wizard",
        tier: 4,
        desc: 'You throw the divining bones or peer into the blackness between the stars, seeking a portent. You can ask the GM one yes or no question. The GM truthfully answers "yes" or "no." If you cast this spell more than once in 24 hours, treat a failed spellcasting check for it as a critical failure, instead.',
        duration: {type: "Instant"},
    },
    {
        name: "Flame Strike",
        range: "Far",
        tier: 4,
        class: "Priest",
        damage: {diceType: "d6", numDice: 2},
        desc: "You call down a holy pillar of fire, immolating one creature you can see within range. The target takes 2d6 damage.",
        duration: {type: "Instant"},
    },
    {
        name: "Freya's Omen",
        range: "Self",
        class: "Seer",
        tier: 4,
        desc: "For the spell's duration, you do not lose the ability to cast a spell if you fail its spellcasting check. If you critically fail a spellcasting check, you may reroll your check once. You must use the new result.",
        duration: {type: "Round", roll: {numDice: 1, diceType: "d6"}},
    },
    {
        name: "Glassbones",
        range: "Close",
        class: "Witch",
        tier: 4,
        desc: "A creature you touch becomes fragile. It takes double damage for the spell's duration.",
        duration: {type: "Focus"},
    },
    {
        name: "Loki's Trickery",
        range: "Near",
        class: "Seer",
        tier: 4,
        desc: "You are filled with Loki's hypnotic guile. Creatures who hear you speak will alter their own beliefs and memories to match your suggestion. Target one creature who can hear and understand you within range. You make one plausible statement, true or not. The target must make a Wisdom check vs. your spellcasting check. If it fails, it now believes what you stated as though it were fact, regardless of what it knows.",
        duration: {type: "Instant"},
    },
    {
        name: "Moonbeam",
        range: "Far",
        class: "Witch",
        tier: 4,
        damage: {diceType: "d6", numDice: 3},
        desc: "A wavering ray of silvery moonlight strikes one creature within far. It takes 3d6 damage.",
        duration: {type: "Instant"},
    },
    {
        name: "Nightmare",
        range: "Plane",
        class: "Witch",
        tier: 4,
        desc: "You visit the dreams of one sleeping creature, sending it heart-stopping nightmares. You can target a creature whose level is less than or equal to half your level rounded down (minimum 1). The target must be sleeping, and you must have seen it before in person. If you successfully focus on this spell for 3 rounds in a row, the creature dies of fright.",
        duration: {type: "Focus"},
    },
    {
        name: "Odin's Wisdom",
        range: "Self",
        class: "Seer",
        tier: 4,
        desc: "For the spell's duration, add your level as an additional bonus to your Wisdom checks and spellcasting checks.",
        duration: {type: "Round", roll: {numDice: 1, diceType: "d6"}},
    },
    {
        name: "Passwall",
        tier: 4,
        class: "Wizard",
        range: "Close",
        desc: "A tunnel of your height opens in a barrier you touch and lasts for the duration. The passage can be up to near distance in length and must be in a straight line.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Pillar Of Salt",
        tier: 4,
        class: "Priest",
        range: "Near",
        desc: "A creature you target turns into a statue made of hardened salt. You can target a creature you can see of LV 5 or less. If you successfully focus on this spell for 3 rounds in a row, the transformation becomes permanent.",
        duration: {type: "Focus"},
    },
    {
        name: "Polymorph",
        tier: 4,
        class: "Wizard, Witch",
        range: "Close",
        desc: "You transform a creature you touch into another natural creature you choose of equal or smaller size. Any gear the target carries melds into its new form. The target gains the creature's physical statistics, but it retains its non-physical statistics. If the target goes to 0 HP, it reverts to its true form at half its prior hit points. You can target any willing creature with this spell, or an unwilling creature whose level is less than or equal to half your level rounded down (minimum 1).",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Regenerate",
        tier: 4,
        class: "Priest",
        range: "Close",
        heal: {diceType: "d4", numDice: 1},
        desc: "A creature you touch regains 1d4 HP on your turn for the duration. This spell also regrows lost body parts.",
        duration: {type: "Focus"},
    },
    {
        name: "Resilient Sphere",
        tier: 4,
        class: "Wizard",
        range: "Close",
        desc: "You conjure a weightless, glassy sphere around you that extends out to close range. For the spell's duration, nothing can pass through or crush the sphere. You can roll the sphere a near distance on your turn.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Stoneskin",
        tier: 4,
        class: "Wizard",
        range: "Self",
        desc: "Your skin becomes like granite. For the spell's duration, your armor class becomes 17 (20 on a critical spellcasting check).",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Telekinesis",
        tier: 4,
        class: "Wizard",
        range: "Far",
        desc: "You lift a creature or object with your mind. Choose a target that weights 1,000 pounds or less. You can move it a near distance in any direction and hold it in place.",
        duration: {type: "Focus"},
    },
    {
        name: "Thor's Thunder",
        range: "Far",
        class: "Seer",
        tier: 4,
        damage: {diceType: "d6", numDice: 3},
        desc: "Thor casts down a bolt of lightning to strike one target. The target takes 3d6 damage.",
        duration: {type: "Instant"},
    },
    {
        name: "Wall Of Force",
        tier: 4,
        class: "Wizard",
        range: "Near",
        desc: "You lift your hands, conjuring a transparent wall of force. The thin wall must be contiguous and can cover a near-sized area in width and length. You choose its shape. Nothing on the same plane can physically pass through the wall.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Wrath",
        tier: 4,
        class: "Priest",
        range: "Self",
        damage: {diceType: "d8", numDice: 1},
        desc: "Your weapons become magical +2 and deal an additional 1d8 damage for the spell's duration.",
        duration: {type: "Round", amt: 10},
    },
    // #################################################################################################################
    // ----------------------------------------------Tier 5 Spells------------------------------------------------------
    // #################################################################################################################
    {
        name: "Anathema",
        range: "Close",
        class: "Witch",
        tier: 5,
        desc: "All allies revile and abandon the creature you touch for 1 day. Each time you or your allies harm the target, its former allies may pass a DC 15 Wisdom check to end the effects of the spell.",
        duration: {type: "Day", amt: 1},
    },
    {
        name: "Antimagic Shell",
        range: "Self",
        class: "Wizard",
        tier: 5,
        desc: "An invisible, near-sized cube of null-magic appears centered on you. Within the cube, no spells can be cast. Magic items and spells have no effect in the zone, and no magic can enter. The cube moves with you. Spells such as dispel magic have no effect on it. Another antimagic shell does not affect this one.",
        duration: {type: "Focus"},
    },
    {
        name: "Create Undead",
        range: "Close",
        class: "Wizard",
        tier: 5,
        desc: "You conjure a vengeful undead creature to do your bidding. When you cast this spell, you choose to summon either a wight or wraith. It appears next to you and is under your control. The undead creature acts on your turn. After 1 day, it melts away into smoke.",
        duration: {type: "Day", subType: "InGame", amt: 1},
    },
    {
        name: "Disintegrate",
        range: "Far",
        class: "Wizard",
        tier: 5,
        desc: "A green ray shoots from your finger and turns a creature or object into ash. A target creature of LV 5 or less instantly dies. If it is LV 6+, it takes 3d8 damage, instead. A non-magical object up to the size of a large tree is destroyed.",
        duration: {type: "Instant"},
    },
    {
        name: "Divine Vengeance",
        range: "Self",
        class: "Priest",
        tier: 5,
        desc: "You become the divine avatar of your god's wrath, wreathed in holy flames or a black aura of smoldering corruption. For the spell's duration, you can fly a near distance, your weapons are magical, and you have a +4 bonus to your weapon attacks and damage.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Dominion",
        range: "Near",
        class: "Priest",
        tier: 5,
        desc: "Mighty beings come to your aid. The beings must have a combined total of 16 levels or less. Chaotic PCs summon demons/devils, and lawful or neutral PCs summon angels. The beings act of free will to aid you on your turn. After 10 rounds, they return to their realms. You cannot cast this spell again until you complete penance.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Dreamwalk",
        range: "Close",
        class: "Witch",
        tier: 5,
        desc: "You and any willing creatures you choose within close range step into the dream of a sleeping creature you name that is on your same plane. You and anyone traveling with you can step out of the creature, appearing next to it as if having teleported there.",
        duration: {type: "Instant"},
    },
    {
        name: "Enfeeble",
        range: "Close",
        class: "Witch",
        tier: 5,
        desc: "A creature you touch has a random stat reduced to 3 (-4) for one week. Roll a d6 to determine which stat: 1. Strength, 2. Dexterity, 3. Constitution, 4. Intelligence, 5. Wisdom, 6. Charisma. If you fail the spellcasting check, you have a random stat reduced to 3 for a week instead.",
        duration: {type: "Day", amt: 1},
    },
    {
        name: "Finger of Death",
        range: "Close",
        class: "Witch",
        tier: 5,
        desc: "One creature you touch of LV 9 or less dies. Treat a failed spellcasting check for this spell as a critical failure, and roll the mishap with disadvantage.",
        duration: {type: "Instant"},
    },
    {
        name: "Heal",
        range: "Close",
        tier: 5,
        class: "Priest",
        desc: "One creature you touch is healed to full HP. You cannot cast this spell again until you complete a rest.",
        duration: {type: "Instant"},
    },
    {
        name: "Hold Monster",
        tier: 5,
        class: "Wizard",
        range: "Near",
        desc: "You paralyze one creature you can see within range. If the target is LV 9+, it may make a STR check vs. your last spellcasting check at the start of its turn to end the spell.",
        duration: {type: "Focus"},
    },
    {
        name: "Judgement",
        tier: 5,
        class: "Priest",
        range: "Close",
        desc: "You instantly banish a creature you touch, sending it and all possessions it carries to face the judgment of your god. You can banish an intelligent creature of LV 10 or less. When the creature returns in 5 rounds, it has been healed to full HP if its deeds pleased your god. It has been reduced to 1 hit point if its deeds angered your god. If your god can't judge its actions, it is unchanged.",
        duration: {type: "Round", amt: 5},
    },
    {
        name: "Mother of Night",
        range: "Self",
        class: "Witch",
        tier: 5,
        desc: "You beseech the Mother of Night to lend you power. Make a single wish, stating it as exactly as possible. Your wish occurs, as interpreted by the GM. If you fail this spellcasting check, the Mother of Night pulls you into The Nightfall for judgment. You can't cast this spell again until you appease her demands.",
        duration: {type: "Instant"},
    },
    {
        name: "Plane Shift",
        tier: 5,
        class: "Priest, Wizard",
        range: "Close",
        desc: "You fold space and time, transporting yourself and all willing creatures within close range to a location on another plane of your choice. Unless you have been to your intended location before, you appear in a random place on the destination plane.",
        duration: {type: "Instant"},
    },
    {
        name: "Power Word Kill",
        tier: 5,
        class: "Wizard",
        range: "Near",
        desc: "You utter the Word of Doom. One creature you target of LV 9 or less dies if it hears you. Treat a failed spellcasting check for this spell as a critical failure, and roll the mishap with disadvantage.",
        duration: {type: "Instant"},
    },
    {
        name: "Prismatic Orb",
        tier: 5,
        class: "Wizard",
        range: "Far",
        damage: {diceType: "d8", numDice: 3},
        desc: "You send a strobing orb of energy streaking toward a target within range. Choose an energy type from fire, cold, or electricity. The orb deals 3d8 damage and delivers a concussive blast of the chosen energy type. If the energy type is anathema to the target's existence (for example, cold energy against a fire elemental), the orb deals double damage to it, instead.",
        duration: {type: "Instant"},
    },
    {
        name: "Prophecy",
        tier: 5,
        class: "Priest",
        range: "Self",
        desc: "You commune directly with your god for guidance. Ask the GM one question. The GM answers the question truthfully using the knowledge your god possesses. Deities are mighty, but not omniscient. You cannot cast this spell again until you complete penance.",
        duration: {type: "Instant"},
    },
    {
        name: "Ragnarok",
        range: "Far",
        class: "Seer",
        tier: 5,
        desc: "You look deep into the strands of fate, learning the final destiny of one soul after the battle of Ragnarok. Do they live, or die? Choose one creature in range. You can only target the same creature with this spell one time. That creature must pass a CON check equal to your spellcasting check or die instantly.",
        duration: {type: "Instant"},
    },
    {
        name: "Scrying",
        tier: 5,
        class: "Wizard, Witch",
        range: "Self",
        desc: "You look into a crystal ball or reflecting pool, calling up images of a distant place. For the spell's duration, you can see and hear a creature or location you choose that is on the same plane. This spell is DC 18 to cast if you try to scry on a creature or location that is unfamiliar to you. Each round, creatures you view may make a Wisdom check vs. your last spellcasting check. On a success, they become aware of your magical observation.",
        duration: {type: "Focus"},
    },
    {
        name: "Shapechange",
        tier: 5,
        class: "Wizard, Witch",
        range: "Self",
        desc: "You transform yourself and any gear you carry into another natural creature you've seen of level 10 or less. You assume the creature's physical statistics, but you retain your non-physical statistics (such as INT, WIS, and CHA). If you go to 0 HP while under the effects of this spell, you revert to your true form at 1 HP.",
        duration: {type: "Focus"},
    },
    {
        name: "Soul Jar",
        range: "Close",
        class: "Witch",
        tier: 5,
        desc: "You transfer the soul of one creature you touch of LV 9 or less into a vessel, such as a jar. The creature's body becomes comatose, but it doesn't die. If the vessel opens or breaks, the creature's soul returns to its body. You can possess the empty body with your own spirit, taking control of it. Your body becomes comatose during this time. If the body dies while you possess it, your soul returns to your body.",
        duration: {type: "Permanent", amt: 0},
    },
    {
        name: "Summon Extraplanar",
        tier: 5,
        class: "Wizard",
        range: "Near",
        desc: "You reach into the outer planes, summoning forth a creature. You summon an elemental or outsider of LV 7 or less. The creature is under your control and acts on your turn. If you lose focus on this spell, you lose control of the creature and it becomes hostile toward you and your allies. You must pass a spellcasting check on your turn to return the creature to the outer planes.",
        duration: {type: "Focus"},
    },
    {
        name: "Teleport",
        tier: 5,
        class: "Wizard",
        range: "Close",
        desc: "You and any willing creatures you choose within close range teleport to a location you specify on your same plane. You can travel to a known teleportation sigil or to a location you've been before. Otherwise, you have a 50% chance of arriving off-target.",
        duration: {type: "Instant"},
    },
    {
        name: "Valkyrie",
        range: "Near",
        class: "Seer",
        tier: 5,
        desc: "You summon a valkyrie to your aid. She appears in a location within near and acts of her own free will to help you. She returns to Valhalla when the spell ends. You can't cast this again until you complete penance.",
        duration: {type: "Round", amt: 10},
    },
    {
        name: "Wish",
        tier: 5,
        class: "Wizard",
        range: "Self",
        desc: "This mighty spell alters reality. Make a single wish, stating it as exactly as possible. Your wish occurs, as interpreted by the GM. Treat a failed spellcasting check for this spell as a critical failure, and roll the mishap with disadvantage.",
        duration: {type: "Instant", amt: 5},
    },
    {
        name: "World Serpent",
        range: "Close",
        class: "Seer",
        tier: 5,
        desc: "The torturous venom of the World Serpent drips from the weapons of a creature you touch. The target deals x2 damage with each attack (x4 on a critical hit) for the spell's duration.",
        duration: {type: "Focus"},
    },
    {
        name: "World Tree",
        range: "Close",
        class: "Seer",
        tier: 5,
        desc: "The roots of the life-giving World Tree wrap around the soul of a creature you touch. For the spell's duration, the target can't be brought below 1 HP.",
        duration: {type: "Focus"},
    },
    // #################################################################################################################
    // ----------------------------------------------Class "Spells"-----------------------------------------------------
    // #################################################################################################################
    {
        name: "Charge",
        tier: 0,
        class: "Desert Rider",
        roll: {numDice: 0, diceType: "d1"},
        uses: {type: "Day", max: 3},
        range: "Self",
        desc: "3/day, you can charge into combat by moving at least near before attacking. Each time you do this, your melee attacks deal double damage that round.",
        duration: {type: "Instant"},
    },
    {
        name: "Demonic Possession",
        tier: 0,
        class: "Knight of St. Ydris",
        stat: "LVL",
        roll: {numDice: 0, diceType: "d1"},
        uses: {type: "Day", max: 3},
        range: "Self",
        desc: "3/day, gain a +1 bonus to your damage rolls that lasts 3 rounds. In addition, add half your level to the damage bonus (round down)",
        duration: {type: "Round", amt: 3},
    },
    {
        name: "Flourish",
        tier: 0,
        class: "Pit Fighter",
        roll: {numDice: 1, diceType: "d6"},
        uses: {type: "Day", max: 3},
        range: "Self",
        desc: "3/day, regain 1d6 HP when you hit an enemy with a melee attack",
        duration: {type: "Instant"},
    },
    {
        name: "Petrifying Gaze",
        tier: 0,
        class: "Basilisk Warrior",
        uses: {type: "Day", max: 1, metadata: {type: "max", stat: "CON"}},
        range: "Self",
        desc: "One creature of your level or less that meets your gaze must pass a DC 15 CON check or be petrified for 1d4 rounds. It still takes damage as normal while petrified.",
        duration: {type: "Round", roll: {numDice: 1, diceType: "d4"}},
    },
    {
        name: "Relentless",
        tier: 0,
        class: "Pit Fighter",
        stat: "CON",
        uses: {type: "Day", max: 3},
        range: "Self",
        desc: "3/day, when you are reduced to 0 HP, make a DC 18 CON check (Implacable applies). On success, you instead go to 1 HP",
        duration: {type: "Instant"},
    },
    {
        name: "Revive Familiar",
        tier: 0,
        class: "Witch",
        stat: "None",
        roll: {numDice: 1, diceType: "d4"},
        range: "Self",
        desc: "If your familiar dies, you can restore it to life by permanently sacrificing 1d4 HP",
        duration: {type: "Instant"},
    },
    {
        name: "Smoke Step",
        tier: 0,
        class: "Ras-Godai",
        stat: "None",
        roll: {numDice: 0, diceType: "d1"},
        uses: {type: "Day", max: 3},
        range: "Self",
        desc: "3/day, teleport to a location you can see within near. This does not use your action",
        duration: {type: "Instant"},
    },
    {
        name: "Turn Undead",
        range: "Near",
        class: "Priest",
        tier: 0,
        desc: "You rebuke undead creatures, forcing them to flee. You must present a holy symbol to cast this spell. Undead creatures within near of you must make a CHA check opposed by your spellcasting check. If a creature fails by 10+ points and is equal to or less than your level, it is destroyed. Otherwise, on a fail, it flees from you for 5 rounds.",
        duration: {type: "Instant"},
    },
    {
        name: "Omen",
        tier: 0,
        class: "Seer",
        uses: {type: "Day", max: 3},
        range: "Self",
        desc: "3/day, you can make a DC 9 WIS check. On a success, gain a luck token (you can't have more than one luck token at a time).",
        duration: {type: "Instant"},
    },
];

const SPELL_COMPENDIUM: { [name: string]: SpellInfo } = {};
for (const s of SPELLS) {
    SPELL_COMPENDIUM[s.name.toLowerCase()] = s;
}
export default SPELL_COMPENDIUM;
